### ISSUE TITLE
[sprint-viz] - Roadmap

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/ricardo#40]
- [ ] Merge with master
- [ ] Drop second line of mirror flows in country view
- [ ] Fix data table and download csv button
